### ISSUE TITLE
Write file to stdout

### ISSUE THREAD

**Issue by slewis-bd** [gruntwork-io/fetch#101]
**Describe the solution you'd like**
When grabbing a file, it would be nice to write the file to stdout. This would be useful when downloading a script and wanting to pipe it to another command.

**Describe alternatives you've considered**
Specifying `/dev/stdout` as the filename. It's ugly but has worked.

**Additional context**
None given

**Comment by tonerdo** [comment]
@slewis-bd #103 has been merged and standard output support is in the v0.4.4 release
