### ISSUE TITLE
Please specify code license

### ISSUE THREAD

**Issue by jareks** [gruntwork-io/fetch#15]
First of all, great thanks for sharing your work!

Would you mind to add an explicit copyright licence to your code? Base on your other repose I assume you wanted to use MIT license for this porject as well :-)

Thanks in advance!

**Comment by brikis98** [comment]
Whoops! Can't believe we forgot that. Thank you for the reminder!

MIT license added: https://github.com/gruntwork-io/fetch/commit/b6e097a2fb21f8a8263753f09bfcb82c45933509
