### ISSUE TITLE
If a repo has no tags, fetch exits with an error

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/fetch#21]
When using `fetch` with `--branch` or `--commit`, you should be able to use a repo that has no tags. But if you do that, you get this error:

```
Received an HTTP 404 Response when attempting to query the repo for its tags.
```

**Comment by aafrey** [comment]
@brikis98 I built this last night and was successful in pulling a a few repo's that did not have tags. I'd like to see if I can replicate, so what command were you using? I used `fetch --branch master --repo https://github.com/aafrey/repo-name /tmp/repo-name` and had no issue :man_shrugging:

**Comment by brikis98** [comment]
@aafrey Perhaps this is a bug with the way the [gruntwork-installer](https://github.com/gruntwork-io/gruntwork-installer) uses `fetch`? @antonbabenko, I believe you were the one to hit this issue, could you provide a bit more detail?

**Comment by antonbabenko** [comment]
Can't reproduce any longer. Must have been issue on my end, because now it works just fine.

**Comment by brikis98** [comment]
Haha, alright then, I'll mark this bug as fixed!
