### ISSUE TITLE
Two Digit Versions

### ISSUE THREAD

**Issue by Keidrych** [gruntwork-io/fetch#24]
Hi All, 

While SemVer requires X.Y.Z it would be great to support X.Y as well as this is also a common version format used in GitHub.

To illustrate:
`fetch --repo="https://github.com/dnephin/dobi" --tag=">=0.9" --release-asset="dobi-windows.exe" %CMDER_ROOT%\bin
`
Fails, while
`fetch --repo="https://github.com/dnephin/dobi" --tag="v0.9" --release-asset="dobi-windows.exe" %CMDER_ROOT%\bin
`
Works but the 'v' is required to make this work.

**Comment by brikis98** [comment]
Seems like a reasonable addition. PRs welcome :)

**Comment by josh-padnick** [comment]
Fetch uses https://github.com/hashicorp/go-version under the hood to satisfy version checks, so I'm guessing that there's a bug in [this function](https://github.com/gruntwork-io/fetch/blob/master/tag.go#L29).
