### ISSUE TITLE
Can't download every release assets and/or by wildcard

### ISSUE THREAD

**Issue by saaguero** [gruntwork-io/fetch#29]
Unless I'm missing something, there is no ability to download every assets for a particular release tag, ie: everything inside https://github.com/gruntwork-io/fetch/releases/tag/v0.1.1

This could happen when the --release-asset is not specified or it is with the star "*" symbol.

Also, it would be nice to be able to specify wildcard/s as part of the --release-asset, and download those assets matching the expression.

**Comment by brikis98** [comment]
Well, you can specify `--release-asset` multiple times to download multiple assets, but there's no support for a wildcard to find all assets automatically. It seems like it could be generally useful, so I'd welcome a PR for it. BTW< what's your use case for that?

**Comment by thapakazi** [comment]
I am in so need of this right now :)

**Comment by nriley** [comment]
FWIW, my use case is projects that embed the version number in the asset names ([example](https://github.com/gilbertchen/duplicacy/releases)).

**Comment by yorinasub17** [comment]
This is now supported using regex: https://github.com/gruntwork-io/fetch/releases/tag/v0.3.3
