### ISSUE TITLE
Use better log formatting

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/fetch#30]
I was debugging an issue in a call to [gruntwork-install](https://github.com/gruntwork-io/gruntwork-installer), and my underlying issue was actually with the command I passed to `fetch`. But the logs output by `fetch` don't make it obvious that it's `fetch` throwing the error. Here's an example:

```
    ubuntu-ami: 2017-11-14 20:47:53 [INFO] [gruntwork-install] Success!
    ubuntu-ami: 2017-11-14 20:47:53 [INFO] [gruntwork-install] Installing from install-kafka...
    ubuntu-ami: 2017-11-14 20:47:53 [INFO] [gruntwork-install] Downloading module install-kafka from https://github.com/gruntwork-io/package-kafka
    ubuntu-ami: ERROR: You must specify exactly one of --tag, --commit, or --branch. Run "fetch --help" for full usage info.
```

The statement `Run "fetch --help" for full usage info.` is an indicator this is a `fetch` error, but the log message should be prefixed with the `fetch` name, as `gruntwork-install` logs are in the example above.

**Comment by robmorgan** [comment]
Fixed in https://github.com/gruntwork-io/fetch/releases/tag/v0.4.0
