### ISSUE TITLE
Use of --source-path can include unwanted files in downloads.

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/fetch#37]
I attempted to download files from a repo that looked like this:

```
- ...
- modules
  - run-x
    - hello.txt
  - run-x-y
  - run-x-y-z
```

using this `fetch` command:

```
fetch --repo <repo> --branch <branch> --source-path "/modules/run-x/" /tmp/
```

At this point, `/tmp` should have only these files:

```
hello.txt
```

But instead, it has these files:

```
-x-y
-x-y-z
hello.txt
```

**Comment by brikis98** [comment]
Fixed by #56 and released in https://github.com/gruntwork-io/fetch/releases/tag/v0.3.7.
