### ISSUE TITLE
Add fetch in brew

### ISSUE THREAD

**Issue by zoispag** [gruntwork-io/fetch#54]
Any change to add fetch as a brew formulae?

**Comment by josh-padnick** [comment]
We'd love to have fetch installable via brew, and we'd certainly welcome a contribution (to the brew repo) that enables this.

**Comment by anentropic** [comment]
and in `apt` `yum` etc... :)

**Comment by andreybleme** [comment]
I have created a pull request for the new formula, but It seems the Homebrew CI can't find the fetch dependencies.
I have performed all the steps and it worked perfectly locally. 

Can anyone have a look at the [broken CI logs](https://github.com/Homebrew/homebrew-core/pull/58950/checks?check_run_id=933915146) and maybe tell me what am I missing?

![image](https://user-images.githubusercontent.com/5385383/89086912-b41bc600-d368-11ea-83e4-51fe8768c6de.png)

**Comment by yorinasub17** [comment]
We haven't updated `fetch` to use go modules yet, so it needs a `dep ensure` call before running `go build`. Have a PR coming shortly that switches over in a moment...

**Comment by yorinasub17** [comment]
Ok just released the version using go modules: https://github.com/gruntwork-io/fetch/releases/tag/v0.3.10

@andreybleme can you see if that version passes the build on brew?

**Comment by andreybleme** [comment]
It passed @yorinasub17 ✅ , just need to wait for it to be merged now.
Thanks.

**Comment by zoispag** [comment]
So, since #71 this can be closed I presume.
Thanks for your work @andreybleme, @yorinasub17 and everyone else involved.
