### ISSUE TITLE
When the tag expression has no acceptable value, fetch defaults to the first tag.

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/fetch#6]
Given:
- The repo has tags: `v0.0.1`,`v0.0.2`,`v0.0.3`
- fetch requested the repo with tag expression `~>0.0.4`

Then:
- fetch will download tag `v0.0.1` of the repo

Instead, fetch should error out and complain that no valid tag was found.

**Comment by brikis98** [comment]
Fixed by #23
