### ISSUE TITLE
Can't download anything from private repo

### ISSUE THREAD

**Issue by Sythsaz** [gruntwork-io/fetch#68]
So I've tried this so many times in so many different ways but the program says that it succeeded but doesn't actually download into the /tmp dir next to the exe. I don't think I am doing anything wrong but here's what I got setup atm.

` @echo off `
`SET GITHUB_OAUTH_TOKEN=123`
`fetch.exe --repo="https://github.com/User/repo" --branch="master" --source-path="/Folder/File.txt" /tmp`
`PAUSE `

I tried it in cmd and in a bat file, the same happens thing both times.

`Downloading latest commit from branch "master" of https://github.com/User/repo ...`
`Extracting files from <repo>/Folder/Text.txt to /tmp ...`
`Download and file extraction complete.`
`Press any key to continue . . .`

Any help would be appreciated.

**Comment by brikis98** [comment]
Is that the full log output, or are you omitting something? Does anything get written to `/tmp`?

**Comment by Sythsaz** [comment]
That's all it outputs to cmd, I don't know if this program has a -v option for getting more output or anything like that. Nothing get's written to the '/tmp' dir.

**Comment by brikis98** [comment]
Hm, it's hard to guess what could be going wrong from this info. Any chance you can create a minimally reproducible case in some repo we can access?

**Comment by Sythsaz** [comment]
I got the same this with this repo as well. Is there a way to see more of what's going on with the program?

`Downloading latest commit from branch "master" of https://github.com/gruntwork-io/fetch ...`
`Extracting files from <repo>/test-fixtures/fetch-test-public-0.0.1.zip to /tmp ...`
`Download and file extraction complete.`
`Press any key to continue . . .`

`@echo off`
`fetch.exe --repo="https://github.com/gruntwork-io/fetch" --branch="master" --source-path="/test-fixtures/fetch-test-public-0.0.1.zip" /tmp`
`PAUSE``

**Comment by brikis98** [comment]
Apologies for the long delay. Lost track of this issue and only stumbled upon it again now. Here's what happens when I run the same command:

```bash
fetch --repo="https://github.com/gruntwork-io/fetch" --branch="master" --source-path="/test-fixtures/fetch-test-public-0.0.1.zip" /tmp

Downloading latest commit from branch "master" of https://github.com/gruntwork-io/fetch ...
Extracting files from <repo>/test-fixtures/fetch-test-public-0.0.1.zip to /tmp ...
ERROR: Error occurred while extracting files from GitHub zip file: Failed to write file: open /tmp: is a directory
```

The issue is that you're telling `fetch` to dowload a file (`fetch-test-public-0.0.1.zip`) but you're pointing the output at a folder. The following works:

```bash
fetch --repo="https://github.com/gruntwork-io/fetch" --branch="master" --source-path="/test-fixtures/fetch-test-public-0.0.1.zip" /tmp/fetch-test-public-0.0.1.zip

Downloading latest commit from branch "master" of https://github.com/gruntwork-io/fetch ...
Extracting files from <repo>/test-fixtures/fetch-test-public-0.0.1.zip to /tmp/foo.zip ...
Download and file extraction complete.
```

I'm not sure why the error messages on Windows aren't showing up.

**Comment by tonerdo** [comment]
Looks like fetch now supports specifying an output folder even for single file downloads.
