### ISSUE TITLE
ARM compiled binary

### ISSUE THREAD

**Issue by rd-aleohl** [gruntwork-io/fetch#82]
Hello,

I will start by saying nice work @gruntwork-ci and all contributors, I really like the simplicity.

Would it be possible to offer pre-compiled binary for arm based platforms?
Raspberry Pi community, and probably Apple M1 will probably appreciate it!

I can compile it for myself but sadly not everyone has the patience or knowledge to do it.

**Comment by brikis98** [comment]
We were waiting on https://github.com/golang/go/issues/38485 to be merged. It looks like it has been merged and will be released with Go 1.16. So we can tackle this when that comes out, which is currently slated for Feb, 2021.

**Comment by mogggggg** [comment]
Do you know when you'll have time to do this @brikis98?

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/fetch/pull/95

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/fetch/releases/tag/v0.4.2
