### ISSUE TITLE
Fetching asset files with + signs causes them not to be found.

### ISSUE THREAD

**Issue by easel** [gruntwork-io/fetch#93]
For a repo+release that has a file named `pipeline-assembly-0.1.0+1-6d47f7c7.jar`,
`--release-asset=pipeline-assembly*` works fine but `--release-asset=pipeline-assembly-0.1.0+1-6d47f7c7.jar` says `Could not find assets matching pipeline-assembly-0.1.0+1-6d47f7c7.jar in release v0.1.0+1-6d47f7c7`.

My assumption is there's some sort of url encoding issue going on with the "+" when querying the github api for the assets on the release.

**Comment by brikis98** [comment]
Thanks for reporting. Does seem like a bug. I'm not sure when we'll be able to get to it, so if someone has a chance to take a look, a PR is very welcome!

**Comment by tonerdo** [comment]
I've been able to reproduce the problem. Looking into a fix
